name: Build OpenWrt Release Image
run-name: Build ${{ inputs.repository }}, version ${{ inputs.version }} for device ${{ inputs.device }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "OpenWrt Repository URL (optional)"
        required: false
        default: "openwrt/openwrt"
      version:
        description: "OpenWrt version to build"
        required: true
        type: choice
        options:
          - 23.05.5
          - 24.10.0
          - 24.10.1
          - 24.10.2
          - 24.10.3
          - 24.10.4
      device:
        description: "The device to build images for"
        required: true
        type: choice
        options:
          - M1300v2
          - MR6350
      ci_directory:
        description: "The directory where the CI repository will be checked out to"
        required: false
        default: "CI"
      openwrt_directory:
        description: "The directory where the OpenWrt repository will be checked out to"
        required: false
        default: "openwrt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          path: ${{ inputs.ci_directory }}

      - name: Checkout OpenWrt Repository
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repository }}
          ref: v${{ inputs.version }}
          path: ${{ inputs.openwrt_directory }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Set up git user
        run: cd ${{ inputs.openwrt_directory }} && git config --global user.name "Hans Wurscht" && git config --global user.email "nobody@home.com"

      - name: Apply git patch
        run: cd ${{ inputs.openwrt_directory }} && git am ../${{ inputs.ci_directory }}/${{ inputs.device }}/${{ inputs.version }}/device.patch

      - name: Update Feeds
        run: cd ${{ inputs.openwrt_directory }} && ./scripts/feeds update -a

      - name: Install Feeds
        run: cd ${{ inputs.openwrt_directory }} && ./scripts/feeds install -a

      - name: Create basic config
        run: |
          source ${{ inputs.ci_directory }}/${{ inputs.device }}/${{ inputs.version }}/device.settings
          wget -O ${{ inputs.openwrt_directory }}/.config "https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/$OPENWRT_TARGET_DIRECTORY/config.buildinfo"

      - name: Make default config
        run: cd ${{ inputs.openwrt_directory }} && make defconfig

      - name: Create vermagic
        # The following command will probably fail, can be ignored. vermagic should be present afterwards anyway
        run: |
          cd ${{ inputs.openwrt_directory }}
          make target/linux/{clean,compile} || echo "Ignore errors, vermagic should still exist"

      - name: Compare vermagic
        run: |
          source ${{ inputs.ci_directory }}/${{ inputs.device }}/${{ inputs.version }}/device.settings
          MANIFEST_FILE=openwrt-${{ inputs.version }}-${OPENWRT_TARGET_DIRECTORY//\//-}.manifest
          wget https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/$OPENWRT_TARGET_DIRECTORY/$MANIFEST_FILE
          EXPECTED_VERMAGIC=$(grep '^kernel - ' "$MANIFEST_FILE" | grep -Eo '[0-9a-fA-F]{32}')
          CURRENT_VERMAGIC=$(find ${{ inputs.openwrt_directory }}/build_dir/ -name .vermagic -exec cat {} \;)
          if [ "$CURRENT_VERMAGIC" == "$EXPECTED_VERMAGIC" ]; then
            echo "Found expected vermagic $EXPECTED_VERMAGIC"
          else
            echo "Current vermagic $CURRENT_VERMAGIC differs from expected vermagic $EXPECTED_VERMAGIC"
            exit 1
          fi

      - name: Download packages
        run: cd ${{ inputs.openwrt_directory }} && make download

      - name: Build Firmware
        run: |
          cd ${{ inputs.openwrt_directory }}
          make -j$(nproc) || make -j1 V=s

      - name: Prepare Artifacts
        run: |
          mkdir output
          source ${{ inputs.ci_directory }}/${{ inputs.device }}/${{ inputs.version }}/device.settings
          cd ${{ inputs.openwrt_directory }}
          rsync -avm --include="config.buildinfo" \
                     --include="feeds.buildinfo" \
                     --include="profiles.json" \
                     --include="sha256sums" \
                     --include="version.buildinfo" \
                     --include="*$OPENWRT_TARGET_PROFILE*" \
                     --exclude="*" bin/targets/*/*/ ../output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: openwrt-${{ inputs.device }}-${{ inputs.version }}
          path: output
