name: Build OpenWrt
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Build
      run: ./build.sh
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-build-output
        path: output
