name: Build OpenWrt Image
run-name: Build ${{ inputs.repository }}, version ${{ inputs.version }} for device ${{ inputs.device }}

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: "The workflow which will be used"
        required: true
        type: choice
        options:
          - Development
          - Release
      repository:
        description: "OpenWrt Repository"
        required: true
        type: choice
        options:
          - RolandoMagico/openwrt
          - openwrt/openwrt
      version:
        description: "OpenWrt version to build"
        required: true
        type: choice
        options:
          - main
          - openwrt-25.12
          - 23.05.5
          - 23.05.6
          - 24.10.0
          - 24.10.1
          - 24.10.2
          - 24.10.3
          - 24.10.4
      device:
        description: "The device to build images for"
        required: true
        type: choice
        options:
          - E30
          - M1300v2
          - MR6350
          - MR9000
      ci_directory:
        description: "The directory where the CI repository will be checked out to"
        required: false
        default: "CI"
      openwrt_directory:
        description: "The directory where the OpenWrt repository will be checked out to"
        required: false
        default: "openwrt"
      rebase:
        description: "Rebase the branch before build"
        required: true
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/GenericBuildWorkflow.yml
    with:
      workflow: ${{ inputs.workflow }}
      repository: ${{ inputs.repository }}
      version: ${{ inputs.version }}
      device: ${{ inputs.device }}
      ci_directory: ${{ inputs.ci_directory }}
      openwrt_directory: ${{ inputs.openwrt_directory }}
      rebase: ${{ inputs.rebase }}
